rvm: 1.9.3
language: objective-c

script: xcodebuild -workspace UITextSubClass.xcworkspace -scheme UITextSubClass -configuration Debug -sdk iphonesimulator7.0 ONLY_ACTIVE_ARCH=YES clean build test | xcpretty -c

notifications:
  email: false
